spring.application.name=waper-api
spring.data.mongodb.uri=mongodb+srv://cartuperez_db_user:Cartuperez19@wapercluster.u0wqisa.mongodb.net/waperdb?retryWrites=true&w=majority&appName=wapercluster
spring.data.mongodb.database=waperdb
